In [2]:
import torch

In [3]:
t = torch.tensor([1., 3., 5., 7., 9., 4.])
print(t)

tensor([1., 3., 5., 7., 9., 4.])


In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([6])
torch.Size([6])


In [6]:
print(t[0],t[3],t[-1])
print(t[1:4], t[3:-1])
print(t[:3], t[4:])

tensor(1.) tensor(7.) tensor(4.)
tensor([3., 5., 7.]) tensor([7., 9.])
tensor([1., 3., 5.]) tensor([9., 4.])


In [8]:
t = torch.tensor([[1.,3.,5.],
                 [7.,9.,11.],
                 [2.,4.,6.],
                 [8.,10.,12.],
                 ])
print(t)

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.],
        [ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [9]:
print(t.dim())
print(t.shape)

2
torch.Size([4, 3])


In [11]:
print(t[0,0], t[3,-1])
print()
print(t[0],t[0,:])
print(t[0].shape)
print()
print(t[:,2])
print(t[:,2].shape)
print()
print(t[1:4,:2])

tensor(1.) tensor(12.)

tensor([1., 3., 5.]) tensor([1., 3., 5.])
torch.Size([3])

tensor([ 5., 11.,  6., 12.])
torch.Size([4])

tensor([[ 7.,  9.],
        [ 2.,  4.],
        [ 8., 10.]])


In [14]:
t = torch.empty([3,4])
print(t)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [15]:
print(torch.empty_like(t))
print(torch.empty(t.shape))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [16]:
t = torch.zeros([3,2,2])
tl = torch.zeros_like(t)
print(t)
print(tl)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [17]:
t = torch.ones([2,3,4])
tl = torch.ones_like(t)
print(t)
print(tl)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [18]:
t = torch.full([1,2,4],7)
tl = torch.full_like(t,9)
print(t)
print(tl)

tensor([[[7, 7, 7, 7],
         [7, 7, 7, 7]]])
tensor([[[9, 9, 9, 9],
         [9, 9, 9, 9]]])


In [19]:
print(torch.rand([3,4]))

tensor([[0.4490, 0.5470, 0.1876, 0.4082],
        [0.2571, 0.4957, 0.9871, 0.0503],
        [0.4540, 0.5196, 0.5266, 0.7369]])


In [20]:
print(torch.randn([2,3]))

tensor([[ 0.4863, -0.2790,  1.2993],
        [ 0.6397, -0.5262,  0.9111]])


In [31]:
print(torch.randint(0,5,[2,4]))

tensor([[3, 0, 4, 3],
        [0, 2, 2, 3]])


In [22]:
print(torch.arange(0,16))
print(torch.arange(start=0, end=16, step=2))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14])


In [32]:
t = torch.arange(12).reshape(3,2,2)
print(t.shape)
print(t)
print(t.sum())

torch.Size([3, 2, 2])
tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])
tensor(66)


In [33]:
print(t.sum(dim=0))
print(t[:,0,0],t[:,0,0].sum())
print(t[:,0,1],t[:,0,1].sum())
print(t[:,1,0],t[:,1,0].sum())
print(t[:,1,1],t[:,1,1].sum())

tensor([[12, 15],
        [18, 21]])
tensor([0, 4, 8]) tensor(12)
tensor([1, 5, 9]) tensor(15)
tensor([ 2,  6, 10]) tensor(18)
tensor([ 3,  7, 11]) tensor(21)


In [34]:
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[ 2,  4],
        [10, 12],
        [18, 20]])
tensor([[ 1,  5],
        [ 9, 13],
        [17, 21]])


In [35]:
t= torch.tensor([[[1.,2.],[3.,4.],[5.,6.]],[[7.,8.],[9.,10.],[11.,12.]]])
print(t.shape)
print(t)

torch.Size([2, 3, 2])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])


In [36]:
print(t.max())
print(t.min())

tensor(12.)
tensor(1.)


In [37]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]),
indices=tensor([[1, 1],
        [1, 1],
        [1, 1]]))


In [39]:
print(t.max(dim=1))

torch.return_types.max(
values=tensor([[ 5.,  6.],
        [11., 12.]]),
indices=tensor([[2, 2],
        [2, 2]]))


In [38]:
v, i = t.max(dim=1)
print(v)
print(i)
print()
print(t[0,:,0])
print(t[0,:,0][2])

tensor([[ 5.,  6.],
        [11., 12.]])
tensor([[2, 2],
        [2, 2]])

tensor([1., 3., 5.])
tensor(5.)


In [50]:
print(t.argmax())
print(t.flatten())
print(t.flatten().max(dim=0))

tensor(11)
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
torch.return_types.max(
values=tensor(12.),
indices=tensor(11))


In [51]:
t = torch.tensor([[[1.,2.,3.],[4.,5.,6.]]])
print(t)
print(t.shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
torch.Size([1, 2, 3])


In [54]:
tp = t.permute([1,2,0])
print(tp)
print(tp.shape)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])
torch.Size([2, 3, 1])


In [55]:
t = torch.rand([3, 1, 4, 1])
print(t.squeeze().shape)
print(t.squeeze(dim=1).shape)
print(t.reshape([3,4]).shape)

torch.Size([3, 4])
torch.Size([3, 4, 1])
torch.Size([3, 4])


In [56]:
t = torch.rand([3,4])
print(t.unsqueeze(dim=0).shape)
print(t.unsqueeze(dim=1).shape)
print(t.view([3,1,4]).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 1, 4])


In [57]:
x = torch.randn(2,3)
print(x)
print(torch.cat((x,x,x), dim=0))
print(torch.cat((x,x,x),0).shape)

tensor([[ 0.8576, -0.4532, -1.2614],
        [-0.5309,  0.1879, -0.5830]])
tensor([[ 0.8576, -0.4532, -1.2614],
        [-0.5309,  0.1879, -0.5830],
        [ 0.8576, -0.4532, -1.2614],
        [-0.5309,  0.1879, -0.5830],
        [ 0.8576, -0.4532, -1.2614],
        [-0.5309,  0.1879, -0.5830]])
torch.Size([6, 3])


In [58]:
print(torch.cat((x,x,x), 1))
print(torch.cat((x,x,x), 1).shape)

tensor([[ 0.8576, -0.4532, -1.2614,  0.8576, -0.4532, -1.2614,  0.8576, -0.4532,
         -1.2614],
        [-0.5309,  0.1879, -0.5830, -0.5309,  0.1879, -0.5830, -0.5309,  0.1879,
         -0.5830]])
torch.Size([2, 9])


In [60]:
x1 = torch.rand(2,3)
x2 = torch.rand(1,3)
x3 = torch.rand(3,3)

print(torch.cat([x1,x2,x3], 0))
print(torch.cat([x1,x2,x3], 0).shape)

tensor([[0.1131, 0.7683, 0.5995],
        [0.3685, 0.6285, 0.6074],
        [0.4705, 0.6166, 0.5303],
        [0.4065, 0.3717, 0.2570],
        [0.5146, 0.5417, 0.7782],
        [0.3818, 0.8832, 0.5678]])
torch.Size([6, 3])


In [61]:
x = torch.randn(2,)
print(x)
print(torch.stack((x,x,x)))
print(torch.stack((x,x,x)).shape)

tensor([-0.5861, -0.2026])
tensor([[-0.5861, -0.2026],
        [-0.5861, -0.2026],
        [-0.5861, -0.2026]])
torch.Size([3, 2])


In [62]:
print(torch.cat((x.unsqueeze(0), x.unsqueeze(0), x.unsqueeze(0)), 0))

tensor([[-0.5861, -0.2026],
        [-0.5861, -0.2026],
        [-0.5861, -0.2026]])


In [63]:
print(torch.stack((x,x,x),dim=1))
print(torch.stack((x,x,x),dim=1).shape)

tensor([[-0.5861, -0.5861, -0.5861],
        [-0.2026, -0.2026, -0.2026]])
torch.Size([2, 3])
